### ISSUE TITLE
Code for review

### ISSUE THREAD

**Issue by patdel0** [fac25/week7-away-days#50]
`App.js` - Unclear what best practices are regarding react-router-dom/ Browser Router

**Comment by reubengt** [comment]
Some of the confusion around this (you'll see articles around the internet with different snippets of code) are because the react router team keeps changing their API - version 6.4 in particular is massively different to anything before it because they are now pitching react router as a routing and data fetching solution rather than just routing.

The way you've implemented it is what I'm familiar with from earlier versions - if it still works for version 6.4 then I'd probably stick to that for simplicity😅
